services:
    postgres:
        container_name: postgres_db
        image: postgres
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: spid
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/volume:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: always
        networks:
            - db

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - '8084:8080'
        networks:
            - db

    backend:
        image: spid-be:latest
        container_name: backend
        build:
            context: ./SpidIntegration
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        networks:
            - db
            - service
        depends_on:
            - postgres

    frontend:
        image: spid-fe:latest
        container_name: frontend
        build:
            context: ./spid-fe
            dockerfile: Dockerfile
        ports:
            - '4200:4200'
        networks:
            - service

networks:
    db:
        name: postgresdb
        driver: bridge
    service:
        name: betofe
        driver: bridge
